import time
# Import the Pyotp and qrcode library for 2-factor authentication
import pyotp
import qrcode
# Import the CSV library
import csv

# Import the cryptography library
from cryptography.fernet import Fernet

# Import the Pandas library
import pandas as pd



'''Function to authenticate user using password and username'''

def authenticate_user(user_id, password):
  #Authenticates a user using their ID and password.
  with open("users.csv", "r") as csvfile:
    reader = csv.reader(csvfile, delimiter=",")
    data = list(reader)

  for row in data:
    if row[0] == user_id and row[1] == password:
      return True

  return False




'''2-Factor Authentication Setup'''

# key to be used to set up 2-Factor Authentication
key = "ExposysMyMessage" 
  
uri = pyotp.totp.TOTP(key).provisioning_uri(
    name='Debajyoti_Talukder',
    issuer_name='ExposysMyMessage')
  
#print(uri)
  
  
# Qr code generation step
qrcode.make(uri).save("qr/qr.png")
  
#Verification starts
  
totp = pyotp.TOTP(key)





'''Now, use the cryptography concept to encrypt message'''
  
# Generate a Fernet key
key = Fernet.generate_key()
# Create a Fernet object with that key
f = Fernet(key)
# Input string to be encrypted
message = "Dear Intern, Welcome to CodeSpeedy. You will receive your offer letter soon."
# Encrypt the string
encrypted_string = f.encrypt(message.encode())
# Decrypt the encrypted string
decrypted_string = f.decrypt(encrypted_string)





'''User Authentication Process Starts... Only valid user can decrypt the message'''

print("\n","Welcome to CodeSpeedy. We have an important message for you !","\n")
  
user_id = input("Enter your user ID: ")
password = input("Enter your password: ")

if authenticate_user(user_id, password):
    
    print("\n","User authenticated successfully. But now, You Need to put the code generated by 2-Factor Authenticator App. Thank You.","\n") 

    if(totp.verify(input(("Enter the Code Generated by 2-Factor Authenticator App : ")))== True):
      print("\n","User Authentication Completed Suceessfull!!. You are a valid user. Welcome!!!","\n")
      print("Your message:", decrypted_string.decode() , "\n")
    else:
       print("\n","Code not matched. Try Again.","\n")
       
else:
    print("\n","User authentication failed.","\n")











